version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=True
      - SECRET_KEY=d_*e4#hpw0^ek23@7csoh6b9pf#x5ggnv7db1)e_x@lz7u-g&4
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    command: celery --app=dcelery worker -l INFO
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    environment:
      - DEBUG=True
      - SECRET_KEY=d_*e4#hpw0^ek23@7csoh6b9pf#x5ggnv7db1)e_x@lz7u-g&4
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery2:
    container_name: celery2
    command: celery -A celery worker -l INFO
    build:
      context: ./celeryworker
    volumes:
      - ./celeryworker:/usr/src/app/
    depends_on:
      - redis
      - django